### ISSUE TITLE
SSP not working?

### ISSUE THREAD

**Issue by kielnino** [nwojke/mcf#4]
I've tried to replicate the min-cost-flow example in python:
```python
import mcf

graph = mcf.Graph()

node_ids = []

costs = [-1., 1., 1., -1.]

for cost in costs:
    node_id = graph.add(cost)
    node_ids.append(node_id)


graph.link(graph.ST, node_ids[0], 0.0)
graph.link(graph.ST, node_ids[1], 1.0)
graph.link(node_ids[2], graph.ST, 1.0)
graph.link(node_ids[3], graph.ST, 1.0)
graph.link(node_ids[0], node_ids[2], 1.0)
graph.link(node_ids[1], node_ids[3], 1.0)

solver = mcf.Solver(graph)
trajectories = solver.run_search(min_flow=1, max_flow=2)
print(trajectories)
```
But this returns an empty list:
```python
[]
```
With the lemon-Solver (`solver = mcf.Solver(graph, 'lemon')`) however, it works as expected:
```python
[[1, 3]]
```

**Comment by nwojke** [comment]
Hi kielnino, thanks for pointing this out. I had written the examples primarily as minimalistic test cases during development and, apparently, left this one in a state where it provokes an unintuitive and undocumented behavior.

It is quite easy to verify that the solution returned by the  LemonSolver is indeed the minimum cost solution for a flow in [1, 3].  The different output for the SSP solver is due to ignoring the `min_flow` parameter. Thus, the SSP solver always searches in [0, max_flow], here, [0, 2]. Since the cost for trajectory [1, 3] is larger than 0, it returns an empty list (trivial solution with 0 cost).

I have modified the example and added documentation to the  [ShortestPathSolver](https://github.com/nwojke/mcf/blob/master/include/mcf/k_shortest_path_solver.hpp#L63) to point this out until I find time to work on this.

Edit: Maybe it would have been better to leave the example as it was and add a note to this issue...

**Comment by kielnino** [comment]
Thank you for the clarification.
